name: Minimal GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Minimal profil - Sadece temel bilgiler
      - name: 📊 Minimal Profil
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ArslanKG
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Istanbul
          filename: metrics-minimal.svg
          
      # Sadece diller
      - name: 🈷️ Programlama Dilleri
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ArslanKG
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_threshold: 3%
          config_timezone: Europe/Istanbul
          filename: metrics-languages-minimal.svg